### ISSUE TITLE
Run frontend and backend on same port

### ISSUE THREAD

**Issue by prank7** [AltCampus/altUpdates#45]

**Comment by praveen-me** [comment]
I did this by using `concurrently`. I am doing this by through making two different sections 
- client 
- backend

And then run the both server by using a single command. 
Can I do that?
 I can't find any thing that helps me to run the both server on the same port.

**Comment by praveen-me** [comment]
![screenshot from 2018-12-09 09-49-30](https://user-images.githubusercontent.com/29889620/49693404-c34c6f80-fb97-11e8-9854-7b0992da67b6.png)
When I want to login through fetch it just added my front-end localhost before the backend url.
What can I do?

**Comment by praveen-me** [comment]
Done with this.

**Comment by prank7** [comment]
Done with PR - https://github.com/AltCampus/altUpdates/pull/52
